package me.ryanw.simplerouter;

import android.content.Context;
import android.content.Intent;

/*
 * This file is part of SimpleRouter, licensed under the MIT License (MIT).
 *
 * Copyright (c) 2015 Ryan W
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
public class SimpleRouter {

    private Context context;
    private static final SimpleRouter simpleRouter = new SimpleRouter();

    /**
     * Gets a globally accessible instance of this router, typical usage.
     * @return A globally accessible instance of this router.
     */
    public static SimpleRouter getSharedRouter() {
        return simpleRouter;
    }

    /**
     * Sets the {@link Context} to be used by all {@link Intent}s generated by the router.
     * @param context The {@link Context} to be used by all {@link Intent}s generated by the router.
     */
    public void setContext(Context context) {
        this.context = context;
    }

    /**
     * Gets the {@link Context} to be used by all {@link Intent}s generated by the router.
     * @return The {@link Context} to be used by all {@link Intent}s generated by the router.
     */
    public Context getContext() {
        return context;
    }
}
